/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("kt.kotlin-application-conventions")

    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dep.management)
    alias(libs.plugins.kotlin.spring)
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
}