server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE