server:
  port: 0
  shutdown: GRACEFUL

context:
  initializer:
    classes: ru.vsu.cs.raspopov.coreservice.users.config.BeansConfig
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:65432/user-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html