server:
  port: 9100
  shutdown: GRACEFUL

context:
  initializer:
    classes: ru.vsu.cs.raspopov.coreservice.users.config.BeansConfig
spring:
  datasource:
    url: jdbc:postgresql://localhost:65432/user-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  exposed:
    generate-ddl: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html