server:
  port: 9200

spring:
  application:
    name: auth-service
  data:
    redis:
      port: 6379
      host: 'localhost'
#  config:
#    import: optional:configserver:http://localhost:8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

jwt-security:
  access-secret-key: 'hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI'
  access-tkn-ttl: 1000000
  refresh-secret-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
  refresh-tkn-ttl: 1000000

service:
  mock: true