server:
  port: 0

#spring:
#  data:
#    redis:
#      port: 9210
#      password: password
#      host: localhost
spring:
  application:
    name: auth-service
#  config:
#    import: optional:configserver:http://localhost:8081
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}

jwt-security:
  access-secret-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
  access-tkn-ttl: 1
  refresh-secret-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
  refresh-tkn-ttl: 1